(ns riemann.common)

(defn unix-to-iso8601-8timezone [unix]
  (clj-time.format/unparse (clj-time.format/with-zone (clj-time.format/formatters :date-time-no-ms) (clj-time.core/time-zone-for-offset 8))
                           (clj-time.coerce/from-long (long (* 1000 unix))))
)

(defn subject [events]
  (str (join " " (keep identity
              [(human-uniq (map :host events) "hosts")
               (case (human-uniq (map :service events) "services")
                        "cpu" "health-CPU"
                        "memory" "health-内存"
                        "disk /" "health-根磁盘"
                        "load" "health-负载"
                        "cdn.sys.processes.ps_count" "进程数"
                        "cdn.sys.load.1m" "主机监控-主机负载"
                        "cdn.sys.tcpconns.tcp_connections.established" "主机监控-并发连接数"
                        "cdn.sys.cpu.user" "CPU监控-单核最高利用率"
                        "cdn.sys.cpuall.user" "CPU监控-CPU利用率"
                        "cdn.sys.cpu.wait" "CPU监控-IO wait"
                        "cdn.sys.disk.disk_ops.read" "磁盘监控-读TPS"
                        "cdn.sys.disk.disk_ops.write" "磁盘监控-写TPS"
                        "cdn.sys.disk.disk_octets.read" "磁盘监控-读速率"
                        "cdn.sys.disk.disk_octets.write" "磁盘监控-写速率"
                        "cdn.sys.df.percent_bytes.used" "磁盘监控-使用率"
                        "cdn.sys.if.if_packets.tx" "网卡监控-出口包量"
                        "cdn.sys.if.if_packets.rx" "网卡监控-入口包量"
                        "cdn.sys.if.if_octets.tx" "网卡监控-出口流量"
                        "cdn.sys.if.if_octets.rx" "网卡监控-入口流量"
                        "cdn.sys.memory.percent.used" "内存监控-内存利用率"
                        "cdn.sys.swap.percent.used" "内存监控-交换分区（swap）利用率"
                        "flowinMin" "流量监控-流入流量"
                        "flowoutMin" "流量监控-流出流量"
                        "flowHitRatioMin" "流量监控-字节命中率"
                        "flowinRateMin" "速率监控-流入速率"
                        "flowoutRateMin" "速率监控-流出速率"
                        "throughputMin" "速率监控-节点吞吐量"
                        "gainRatioMin" "速率监控-增益比"
                        "reqMin" "业务请求监控-业务请求数"
                        "reqOkMin" "业务请求监控-请求成功数"
                        "reqHitRatioMin" "业务请求监控-请求成功率"
                        "req4CodeMin" "业务请求监控-客户端错误数"
                        "req5CodeMin" "业务请求监控-服务端错误数"
                        "serveDelayMin" "业务请求监控-首字节响应时延"
                        "reqbackMin" "回源请求监控-回源请求数"
                        "reqbackOkMin" "回源请求监控-回源成功数"
                        "back4CodeMin" "回源请求监控-回源客户端错误数"
                        "back5CodeMin" "回源请求监控-回源服务端错误数"
                        "req100CodeMin" "业务请求监控-业务请求100响应码"
                        "req101CodeMin" "业务请求监控-业务请求101响应码"
                        "req200CodeMin" "业务请求监控-业务请求200响应码"
                        "req201CodeMin" "业务请求监控-业务请求201响应码"
                        "req202CodeMin" "业务请求监控-业务请求202响应码"
                        "req203CodeMin" "业务请求监控-业务请求203响应码"
                        "req204CodeMin" "业务请求监控-业务请求204响应码"
                        "req205CodeMin" "业务请求监控-业务请求205响应码"
                        "req206CodeMin" "业务请求监控-业务请求206响应码"
                        "req300CodeMin" "业务请求监控-业务请求300响应码"
                        "req301CodeMin" "业务请求监控-业务请求301响应码"
                        "req302CodeMin" "业务请求监控-业务请求302响应码"
                        "req303CodeMin" "业务请求监控-业务请求303响应码"
                        "req304CodeMin" "业务请求监控-业务请求304响应码"
                        "req305CodeMin" "业务请求监控-业务请求305响应码"
                        "req307CodeMin" "业务请求监控-业务请求307响应码"
                        "req400CodeMin" "业务请求监控-业务请求400响应码"
                        "req401CodeMin" "业务请求监控-业务请求401响应码"
                        "req402CodeMin" "业务请求监控-业务请求402响应码"
                        "req403CodeMin" "业务请求监控-业务请求403响应码"
                        "req404CodeMin" "业务请求监控-业务请求404响应码"
                        "req405CodeMin" "业务请求监控-业务请求405响应码"
                        "req406CodeMin" "业务请求监控-业务请求406响应码"
                        "req407CodeMin" "业务请求监控-业务请求407响应码"
                        "req408CodeMin" "业务请求监控-业务请求408响应码"
                        "req409CodeMin" "业务请求监控-业务请求409响应码"
                        "req410CodeMin" "业务请求监控-业务请求410响应码"
                        "req411CodeMin" "业务请求监控-业务请求411响应码"
                        "req412CodeMin" "业务请求监控-业务请求412响应码"
                        "req413CodeMin" "业务请求监控-业务请求413响应码"
                        "req414CodeMin" "业务请求监控-业务请求414响应码"
                        "req415CodeMin" "业务请求监控-业务请求415响应码"
                        "req416CodeMin" "业务请求监控-业务请求416响应码"
                        "req417CodeMin" "业务请求监控-业务请求417响应码"
                        "req500CodeMin" "业务请求监控-业务请求500响应码"
                        "req501CodeMin" "业务请求监控-业务请求501响应码"
                        "req502CodeMin" "业务请求监控-业务请求502响应码"
                        "req503CodeMin" "业务请求监控-业务请求503响应码"
                        "req504CodeMin" "业务请求监控-业务请求504响应码"
                        "req505CodeMin" "业务请求监控-业务请求505响应码"
                        "req502RatioMin" "业务请求监控-业务请求502响应码比率"
                        "req5RatioMin" "业务请求监控-服务端错误比率"
                        "back100CodeMin" "业务请求监控-回源请求100响应码"
                        "back101CodeMin" "业务请求监控-回源请求101响应码"
                        "back200CodeMin" "业务请求监控-回源请求200响应码"
                        "back201CodeMin" "业务请求监控-回源请求201响应码"
                        "back202CodeMin" "业务请求监控-回源请求202响应码"
                        "back203CodeMin" "业务请求监控-回源请求203响应码"
                        "back204CodeMin" "业务请求监控-回源请求204响应码"
                        "back205CodeMin" "业务请求监控-回源请求205响应码"
                        "back206CodeMin" "业务请求监控-回源请求206响应码"
                        "back300CodeMin" "业务请求监控-回源请求300响应码"
                        "back301CodeMin" "业务请求监控-回源请求301响应码"
                        "back302CodeMin" "业务请求监控-回源请求302响应码"
                        "back303CodeMin" "业务请求监控-回源请求303响应码"
                        "back304CodeMin" "业务请求监控-回源请求304响应码"
                        "back305CodeMin" "业务请求监控-回源请求305响应码"
                        "back307CodeMin" "业务请求监控-回源请求307响应码"
                        "back400CodeMin" "业务请求监控-回源请求400响应码"
                        "back401CodeMin" "业务请求监控-回源请求401响应码"
                        "back402CodeMin" "业务请求监控-回源请求402响应码"
                        "back403CodeMin" "业务请求监控-回源请求403响应码"
                        "back404CodeMin" "业务请求监控-回源请求404响应码"
                        "back405CodeMin" "业务请求监控-回源请求405响应码"
                        "back406CodeMin" "业务请求监控-回源请求406响应码"
                        "back407CodeMin" "业务请求监控-回源请求407响应码"
                        "back408CodeMin" "业务请求监控-回源请求408响应码"
                        "back409CodeMin" "业务请求监控-回源请求409响应码"
                        "back410CodeMin" "业务请求监控-回源请求410响应码"
                        "back411CodeMin" "业务请求监控-回源请求411响应码"
                        "back412CodeMin" "业务请求监控-回源请求412响应码"
                        "back413CodeMin" "业务请求监控-回源请求413响应码"
                        "back414CodeMin" "业务请求监控-回源请求414响应码"
                        "back415CodeMin" "业务请求监控-回源请求415响应码"
                        "back416CodeMin" "业务请求监控-回源请求416响应码"
                        "back417CodeMin" "业务请求监控-回源请求417响应码"
                        "back500CodeMin" "业务请求监控-回源请求500响应码"
                        "back501CodeMin" "业务请求监控-回源请求501响应码"
                        "back502CodeMin" "业务请求监控-回源请求502响应码"
                        "back503CodeMin" "业务请求监控-回源请求503响应码"
                        "back504CodeMin" "业务请求监控-回源请求504响应码"
                        "back505CodeMin" "业务请求监控-回源请求505响应码"
                        (human-uniq (map :service events) "services")
               )
               ;(human-uniq (map :state events) "states")
              ]
            )
        )
        "告警"
  )
)

(defn body [events]
  (join "\n\n\n"
        (map
          (fn [event]
            (str
              "告警时间：\t" (unix-to-iso8601-8timezone (:time event)) "\n"
              "主机名称：\t" (:host event) "\n"
              "告警指标：\t" (case (:service event)
                        "cpu" "health-CPU"
                        "memory" "health-内存"
                        "disk /" "health-根磁盘"
                        "load" "health-负载"
                        "cdn.sys.processes.ps_count" "进程数"
                        "cdn.sys.load.1m" "主机监控-主机负载"
                        "cdn.sys.tcpconns.tcp_connections.established" "主机监控-并发连接数"
                        "cdn.sys.cpu.user" "CPU监控-单核最高利用率"
                        "cdn.sys.cpuall.user" "CPU监控-CPU利用率"
                        "cdn.sys.cpu.wait" "CPU监控-IO wait"
                        "cdn.sys.disk.disk_ops.read" "磁盘监控-读TPS"
                        "cdn.sys.disk.disk_ops.write" "磁盘监控-写TPS"
                        "cdn.sys.disk.disk_octets.read" "磁盘监控-读速率"
                        "cdn.sys.disk.disk_octets.write" "磁盘监控-写速率"
                        "cdn.sys.df.percent_bytes.used" "磁盘监控-使用率"
                        "cdn.sys.if.if_packets.tx" "网卡监控-出口包量"
                        "cdn.sys.if.if_packets.rx" "网卡监控-入口包量"
                        "cdn.sys.if.if_octets.tx" "网卡监控-出口流量"
                        "cdn.sys.if.if_octets.rx" "网卡监控-入口流量"
                        "cdn.sys.memory.percent.used" "内存监控-内存利用率"
                        "cdn.sys.swap.percent.used" "内存监控-交换分区（swap）利用率"
                        "flowinMin" "流量监控-流入流量"
                        "flowoutMin" "流量监控-流出流量"
                        "flowHitRatioMin" "流量监控-字节命中率"
                        "flowinRateMin" "速率监控-流入速率"
                        "flowoutRateMin" "速率监控-流出速率"
                        "throughputMin" "速率监控-节点吞吐量"
                        "gainRatioMin" "速率监控-增益比"
                        "reqMin" "业务请求监控-业务请求数"
                        "reqOkMin" "业务请求监控-请求成功数"
                        "reqHitRatioMin" "业务请求监控-请求成功率"
                        "req4CodeMin" "业务请求监控-客户端错误数"
                        "req5CodeMin" "业务请求监控-服务端错误数"
                        "serveDelayMin" "业务请求监控-首字节响应时延"
                        "reqbackMin" "回源请求监控-回源请求数"
                        "reqbackOkMin" "回源请求监控-回源成功数"
                        "back4CodeMin" "回源请求监控-回源客户端错误数"
                        "back5CodeMin" "回源请求监控-回源服务端错误数"
                        "req100CodeMin" "业务请求监控-业务请求100响应码"
                        "req101CodeMin" "业务请求监控-业务请求101响应码"
                        "req200CodeMin" "业务请求监控-业务请求200响应码"
                        "req201CodeMin" "业务请求监控-业务请求201响应码"
                        "req202CodeMin" "业务请求监控-业务请求202响应码"
                        "req203CodeMin" "业务请求监控-业务请求203响应码"
                        "req204CodeMin" "业务请求监控-业务请求204响应码"
                        "req205CodeMin" "业务请求监控-业务请求205响应码"
                        "req206CodeMin" "业务请求监控-业务请求206响应码"
                        "req300CodeMin" "业务请求监控-业务请求300响应码"
                        "req301CodeMin" "业务请求监控-业务请求301响应码"
                        "req302CodeMin" "业务请求监控-业务请求302响应码"
                        "req303CodeMin" "业务请求监控-业务请求303响应码"
                        "req304CodeMin" "业务请求监控-业务请求304响应码"
                        "req305CodeMin" "业务请求监控-业务请求305响应码"
                        "req307CodeMin" "业务请求监控-业务请求307响应码"
                        "req400CodeMin" "业务请求监控-业务请求400响应码"
                        "req401CodeMin" "业务请求监控-业务请求401响应码"
                        "req402CodeMin" "业务请求监控-业务请求402响应码"
                        "req403CodeMin" "业务请求监控-业务请求403响应码"
                        "req404CodeMin" "业务请求监控-业务请求404响应码"
                        "req405CodeMin" "业务请求监控-业务请求405响应码"
                        "req406CodeMin" "业务请求监控-业务请求406响应码"
                        "req407CodeMin" "业务请求监控-业务请求407响应码"
                        "req408CodeMin" "业务请求监控-业务请求408响应码"
                        "req409CodeMin" "业务请求监控-业务请求409响应码"
                        "req410CodeMin" "业务请求监控-业务请求410响应码"
                        "req411CodeMin" "业务请求监控-业务请求411响应码"
                        "req412CodeMin" "业务请求监控-业务请求412响应码"
                        "req413CodeMin" "业务请求监控-业务请求413响应码"
                        "req414CodeMin" "业务请求监控-业务请求414响应码"
                        "req415CodeMin" "业务请求监控-业务请求415响应码"
                        "req416CodeMin" "业务请求监控-业务请求416响应码"
                        "req417CodeMin" "业务请求监控-业务请求417响应码"
                        "req500CodeMin" "业务请求监控-业务请求500响应码"
                        "req501CodeMin" "业务请求监控-业务请求501响应码"
                        "req502CodeMin" "业务请求监控-业务请求502响应码"
                        "req503CodeMin" "业务请求监控-业务请求503响应码"
                        "req504CodeMin" "业务请求监控-业务请求504响应码"
                        "req505CodeMin" "业务请求监控-业务请求505响应码"
                        "req502RatioMin" "业务请求监控-业务请求502响应码比率"
                        "req5RatioMin" "业务请求监控-服务端错误比率"
                        "back100CodeMin" "业务请求监控-回源请求100响应码"
                        "back101CodeMin" "业务请求监控-回源请求101响应码"
                        "back200CodeMin" "业务请求监控-回源请求200响应码"
                        "back201CodeMin" "业务请求监控-回源请求201响应码"
                        "back202CodeMin" "业务请求监控-回源请求202响应码"
                        "back203CodeMin" "业务请求监控-回源请求203响应码"
                        "back204CodeMin" "业务请求监控-回源请求204响应码"
                        "back205CodeMin" "业务请求监控-回源请求205响应码"
                        "back206CodeMin" "业务请求监控-回源请求206响应码"
                        "back300CodeMin" "业务请求监控-回源请求300响应码"
                        "back301CodeMin" "业务请求监控-回源请求301响应码"
                        "back302CodeMin" "业务请求监控-回源请求302响应码"
                        "back303CodeMin" "业务请求监控-回源请求303响应码"
                        "back304CodeMin" "业务请求监控-回源请求304响应码"
                        "back305CodeMin" "业务请求监控-回源请求305响应码"
                        "back307CodeMin" "业务请求监控-回源请求307响应码"
                        "back400CodeMin" "业务请求监控-回源请求400响应码"
                        "back401CodeMin" "业务请求监控-回源请求401响应码"
                        "back402CodeMin" "业务请求监控-回源请求402响应码"
                        "back403CodeMin" "业务请求监控-回源请求403响应码"
                        "back404CodeMin" "业务请求监控-回源请求404响应码"
                        "back405CodeMin" "业务请求监控-回源请求405响应码"
                        "back406CodeMin" "业务请求监控-回源请求406响应码"
                        "back407CodeMin" "业务请求监控-回源请求407响应码"
                        "back408CodeMin" "业务请求监控-回源请求408响应码"
                        "back409CodeMin" "业务请求监控-回源请求409响应码"
                        "back410CodeMin" "业务请求监控-回源请求410响应码"
                        "back411CodeMin" "业务请求监控-回源请求411响应码"
                        "back412CodeMin" "业务请求监控-回源请求412响应码"
                        "back413CodeMin" "业务请求监控-回源请求413响应码"
                        "back414CodeMin" "业务请求监控-回源请求414响应码"
                        "back415CodeMin" "业务请求监控-回源请求415响应码"
                        "back416CodeMin" "业务请求监控-回源请求416响应码"
                        "back417CodeMin" "业务请求监控-回源请求417响应码"
                        "back500CodeMin" "业务请求监控-回源请求500响应码"
                        "back501CodeMin" "业务请求监控-回源请求501响应码"
                        "back502CodeMin" "业务请求监控-回源请求502响应码"
                        "back503CodeMin" "业务请求监控-回源请求503响应码"
                        "back504CodeMin" "业务请求监控-回源请求504响应码"
                        "back505CodeMin" "业务请求监控-回源请求505响应码"
                        (:service event)
                                  )"\n"
              "当前数值：\t"
              (if (ratio? (:metric event))
                (double (:metric event))
                (:metric event)) "\n"
              "标签列表：\t[" (join ", " (:tags event)) "]\n"
              "特有属性：\t" (custom-attributes event) "\n\n"
              "详细描述：\t" (:description event)
            )
          )
          events
        )
  )
)

(ns riemann.config)
